export const data = JSON.parse("{\"key\":\"v-1fd1f647\",\"path\":\"/JavaScript/js%E4%BD%8D%E8%BF%90%E7%AE%97.html\",\"title\":\"JavaScript中的位运算\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"JavaScript中的位运算\",\"icon\":\"javascript\",\"order\":4,\"category\":[\"javascript\"],\"tag\":[\"javascript\"],\"description\":\"JavaScript 中的位运算 在 **JavaScript** 中, **移位运算**就是对二进制进行有规律低移位。在本篇中, 将要简要总结 **js位运算** 的常用方法及技巧。在 **算法中的整除和整乘** 常以 **位运算** 代替 **`Math`** 方法，速度确实提升很多。常用的位移运算有三种: &lt;&lt; //左移 &gt;&gt; //带符号右移 &gt;&gt;&gt; //无符号右移\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/front-end-life/JavaScript/js%E4%BD%8D%E8%BF%90%E7%AE%97.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Huy's Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"JavaScript中的位运算\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"JavaScript 中的位运算 在 **JavaScript** 中, **移位运算**就是对二进制进行有规律低移位。在本篇中, 将要简要总结 **js位运算** 的常用方法及技巧。在 **算法中的整除和整乘** 常以 **位运算** 代替 **`Math`** 方法，速度确实提升很多。常用的位移运算有三种: &lt;&lt; //左移 &gt;&gt; //带符号右移 &gt;&gt;&gt; //无符号右移\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"javascript\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"JavaScript中的位运算\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"左移 <<\",\"slug\":\"左移\",\"link\":\"#左移\",\"children\":[]},{\"level\":2,\"title\":\"带符号右移 >>\",\"slug\":\"带符号右移\",\"link\":\"#带符号右移\",\"children\":[]},{\"level\":2,\"title\":\"无符号右移运算符（>>>）\",\"slug\":\"无符号右移运算符\",\"link\":\"#无符号右移运算符\",\"children\":[]},{\"level\":2,\"title\":\"参考\",\"slug\":\"参考\",\"link\":\"#参考\",\"children\":[]}],\"readingTime\":{\"minutes\":1.78,\"words\":535},\"filePathRelative\":\"JavaScript/js位运算.md\",\"excerpt\":\"<h1> JavaScript 中的位运算</h1>\\n<pre><code>在 **JavaScript** 中, **移位运算**就是对二进制进行有规律低移位。在本篇中, 将要简要总结 **js位运算** 的常用方法及技巧。在 **算法中的整除和整乘** 常以 **位运算** 代替 **`Math`** 方法，速度确实提升很多。常用的位移运算有三种:\\n</code></pre>\\n<div class=\\\"language-javascript line-numbers-mode\\\" data-ext=\\\"js\\\"><pre class=\\\"language-javascript\\\"><code><span class=\\\"token operator\\\">&lt;&lt;</span>     <span class=\\\"token comment\\\">//左移</span>\\n<span class=\\\"token operator\\\">&gt;&gt;</span>     <span class=\\\"token comment\\\">//带符号右移</span>\\n<span class=\\\"token operator\\\">&gt;&gt;&gt;</span>    <span class=\\\"token comment\\\">//无符号右移</span>\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
