export const data = JSON.parse("{\"key\":\"v-2f5b5962\",\"path\":\"/JavaScript/%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83%E5%92%8C%E8%87%AA%E5%8A%A8%E6%A0%BC%E5%BC%8F%E5%8C%96.html\",\"title\":\"代码规范和自动格式化\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"代码规范和自动格式化\",\"icon\":\"javascript\",\"order\":1,\"category\":[\"javascript\"],\"tag\":[\"javascript\"],\"description\":\"代码规范和自动格式化 ​ 在团队开发中，统一代码规范是必不可少的。ESlint 是我们前端工程化中代码检测的一款常用工具。它不仅可以检测 JS 还支持 Vue 和 JSX 。 安装和使用 环境要求: Node.js (&gt;=6.14), npm version 3+。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/front-end-life/JavaScript/%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83%E5%92%8C%E8%87%AA%E5%8A%A8%E6%A0%BC%E5%BC%8F%E5%8C%96.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Huy's Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"代码规范和自动格式化\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"代码规范和自动格式化 ​ 在团队开发中，统一代码规范是必不可少的。ESlint 是我们前端工程化中代码检测的一款常用工具。它不仅可以检测 JS 还支持 Vue 和 JSX 。 安装和使用 环境要求: Node.js (&gt;=6.14), npm version 3+。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"javascript\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"代码规范和自动格式化\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"安装和使用\",\"slug\":\"安装和使用\",\"link\":\"#安装和使用\",\"children\":[{\"level\":3,\"title\":\"ESlint 配合 VScode 插件使用\",\"slug\":\"eslint-配合-vscode-插件使用\",\"link\":\"#eslint-配合-vscode-插件使用\",\"children\":[]},{\"level\":3,\"title\":\"设置 Prettier\",\"slug\":\"设置-prettier\",\"link\":\"#设置-prettier\",\"children\":[]},{\"level\":3,\"title\":\"配合 Typescript\",\"slug\":\"配合-typescript\",\"link\":\"#配合-typescript\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.51,\"words\":1054},\"filePathRelative\":\"JavaScript/代码规范和自动格式化.md\",\"excerpt\":\"<h1> 代码规范和自动格式化</h1>\\n<p>​ 在团队开发中，统一代码规范是必不可少的。<a href=\\\"https://cn.eslint.org/docs/user-guide/configuring\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\"><strong>ESlint</strong></a> 是我们前端工程化中代码检测的一款常用工具。它不仅可以检测 <code>JS</code> 还支持 <code>Vue</code> 和 <code>JSX</code> 。</p>\\n<h2> 安装和使用</h2>\\n<p>环境要求: <a href=\\\"https://nodejs.org/zh-cn/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">Node.js</a> (&gt;=6.14), npm version 3+。</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
