export const themeData = JSON.parse("{\"encrypt\":{\"config\":{\"/demo/encrypt.html\":[\"$2a$10$vcIQBk4Sze.ueQSb5IJj8uWuOkQAT8H40BPT6ZzX7qElgCRMsA5XW\"],\"/zh/demo/encrypt.html\":[\"$2a$10$Euus1TVHnqwBjX8dwlBaIeT3eAieSKF6UPzCVUaLiqCMMBj/NxTTG\"]}},\"blog\":{\"medias\":{\"GitHub\":\"https://example.com\"}},\"locales\":{\"/\":{\"lang\":\"en-US\",\"navbarLocales\":{\"langName\":\"English\",\"selectLangAriaLabel\":\"Select language\"},\"metaLocales\":{\"author\":\"Author\",\"date\":\"Writing Date\",\"origin\":\"Original\",\"views\":\"Page views\",\"category\":\"Category\",\"tag\":\"Tag\",\"readingTime\":\"Reading Time\",\"words\":\"Words\",\"toc\":\"On This Page\",\"prev\":\"Prev\",\"next\":\"Next\",\"lastUpdated\":\"Last update\",\"contributors\":\"Contributors\",\"editLink\":\"Edit this page on GitHub\"},\"blogLocales\":{\"article\":\"Articles\",\"articleList\":\"Article List\",\"category\":\"Category\",\"tag\":\"Tag\",\"timeline\":\"Timeline\",\"timelineTitle\":\"Yesterday Once More!\",\"all\":\"All\",\"intro\":\"Personal Intro\",\"star\":\"Star\"},\"paginationLocales\":{\"prev\":\"Prev\",\"next\":\"Next\",\"navigate\":\"Jump to\",\"action\":\"Go\",\"errorText\":\"Please enter a number between 1 and $page !\"},\"outlookLocales\":{\"themeColor\":\"Theme Color\",\"darkmode\":\"Theme Mode\",\"fullscreen\":\"Full Screen\"},\"encryptLocales\":{\"iconLabel\":\"Page Encrypted\",\"placeholder\":\"Enter password\",\"remember\":\"Remember password\",\"errorHint\":\"Please enter the correct password!\"},\"routeLocales\":{\"skipToContent\":\"Skip to main content\",\"notFoundTitle\":\"Page not found\",\"notFoundMsg\":[\"There’s nothing here.\",\"How did we get here?\",\"That’s a Four-Oh-Four.\",\"Looks like we've got some broken links.\"],\"back\":\"Go back\",\"home\":\"Take me home\",\"openInNewWindow\":\"Open in new window\"},\"author\":{\"name\":\"Huy\",\"url\":\"https://github.com/rayadaschn\"},\"logo\":\"/logo.png\",\"docsDir\":\"docs\",\"navbar\":[\"/\",{\"icon\":\"markdown\",\"text\":\"JavaScript\",\"prefix\":\"JavaScript/\",\"link\":\"/JavaScript/\"},{\"icon\":\"discover\",\"text\":\"CSS\",\"prefix\":\"CSS/\",\"link\":\"/CSS/\"},{\"text\":\"Mac/Linux配置\",\"icon\":\"note\",\"prefix\":\"Mac&Linux配置/\",\"link\":\"/Mac&Linux配置/\"}],\"sidebar\":{\"/\":[\"\",{\"icon\":\"markdown\",\"text\":\"JavaScript\",\"prefix\":\"JavaScript/\",\"link\":\"JavaScript/\",\"children\":\"structure\"},{\"icon\":\"discover\",\"text\":\"CSS\",\"prefix\":\"CSS/\",\"link\":\"CSS/\",\"children\":\"structure\"},{\"text\":\"小程序\",\"icon\":\"note\",\"prefix\":\"小程序/\",\"children\":\"structure\"},{\"text\":\"Mac/Linux配置\",\"icon\":\"note\",\"prefix\":\"Mac&Linux配置/\",\"link\":\"/Mac&Linux配置/\",\"children\":\"structure\"},\"优质博文\"]},\"footer\":\"Default footer\",\"displayFooter\":true,\"blog\":{\"description\":\"A FrontEnd programmer~\",\"intro\":\"/intro.html\"}}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
