name: deploy-gh-pages

on:
  push:
    branches:
      - sourcecode
    paths-ignore: # 下列文件的变更不触发部署
      - README.md
      - LICENSE
  pull_request:
    branches:
      - sourcecode
    types: [closed]
  schedule:
    - cron: '30 5,11 * * *'

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # repo-token: ${{ secrets.DEPLOY_TOKEN }}
          # submodules: true

      # - name: 设置 Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      #     cache: npm

       # find yarn cache
    - name: Get yarn cache path
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    # update cache
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

      - name: 安装依赖
        run: yarn install

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          yarn docs:build
          > docs/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          #  文档部署到的分支名称
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: master
          FOLDER: docs/.vuepress/dist/
          CLEAN: true
      # 自动部署到阿里云服务器
      - name: deploy to aliyun
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # scp参数
          ARGS: '-rltgoDzvO --delete'
          # 源目录，编译后生成的文件目录
          SOURCE: docs/.vuepress/dist/
          # 服务器ip
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          # 用户
          REMOTE_USER: root
          # 目标地址
          TARGET: /var/www
