name: 部署文档

on:
  push:
    branches:
      - sourcecode # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE
    pull_request:
      branches:
        - sourcecode # 只在master上push触发部署
      types: [closed]
    schedule:
      # Runs everyday at 3:00 AM
      - cron: "0 3 * * *"

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repo-token: ${{ secrets.DEPLOY_TOKEN }}
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: 安装依赖
        run: npm ci

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          #  文档部署到的分支名称
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: src/.vuepress/dist/
          CLEAN: true
